name: emobilier
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  #firebase: ^5.0.0
  transformer_page_view:
  unicorndial: "^1.1.5"
  image_picker: 
  flutter_mailer:
  sqflite:
  path_provider: 
  intro_views_flutter:
  flutter_swiper: 

 
  cupertino_icons: ^0.1.2
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

 
  uses-material-design: true


  assets:
   - assets/images/salon.jpg
   - assets/images/swipe-right.png
   - assets/images/wallet1.png
   - assets/images/wallet2.png
   - assets/images/wallet3.png
   - assets/images/logo.png
   - assets/images/room1.jpg
   - assets/images/room2.jpg
   - assets/images/room3.jpg
   - assets/images/room4.jpg

  

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  
